// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: wiresafe.proto

package wiresafe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workingkey string `protobuf:"bytes,1,opt,name=workingkey,proto3" json:"workingkey,omitempty"`
}

func (x *InitReply) Reset() {
	*x = InitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wiresafe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitReply) ProtoMessage() {}

func (x *InitReply) ProtoReflect() protoreflect.Message {
	mi := &file_wiresafe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitReply.ProtoReflect.Descriptor instead.
func (*InitReply) Descriptor() ([]byte, []int) {
	return file_wiresafe_proto_rawDescGZIP(), []int{0}
}

func (x *InitReply) GetWorkingkey() string {
	if x != nil {
		return x.Workingkey
	}
	return ""
}

type KeySpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Safename string `protobuf:"bytes,1,opt,name=safename,proto3" json:"safename,omitempty"`
	Keyname  string `protobuf:"bytes,2,opt,name=keyname,proto3" json:"keyname,omitempty"`
}

func (x *KeySpec) Reset() {
	*x = KeySpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wiresafe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySpec) ProtoMessage() {}

func (x *KeySpec) ProtoReflect() protoreflect.Message {
	mi := &file_wiresafe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySpec.ProtoReflect.Descriptor instead.
func (*KeySpec) Descriptor() ([]byte, []int) {
	return file_wiresafe_proto_rawDescGZIP(), []int{1}
}

func (x *KeySpec) GetSafename() string {
	if x != nil {
		return x.Safename
	}
	return ""
}

func (x *KeySpec) GetKeyname() string {
	if x != nil {
		return x.Keyname
	}
	return ""
}

type EncryptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspec   *KeySpec `protobuf:"bytes,1,opt,name=keyspec,proto3" json:"keyspec,omitempty"`
	Plaintext []byte   `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
}

func (x *EncryptReq) Reset() {
	*x = EncryptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wiresafe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptReq) ProtoMessage() {}

func (x *EncryptReq) ProtoReflect() protoreflect.Message {
	mi := &file_wiresafe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptReq.ProtoReflect.Descriptor instead.
func (*EncryptReq) Descriptor() ([]byte, []int) {
	return file_wiresafe_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptReq) GetKeyspec() *KeySpec {
	if x != nil {
		return x.Keyspec
	}
	return nil
}

func (x *EncryptReq) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type EncryptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ciphertext []byte `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (x *EncryptResp) Reset() {
	*x = EncryptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wiresafe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResp) ProtoMessage() {}

func (x *EncryptResp) ProtoReflect() protoreflect.Message {
	mi := &file_wiresafe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResp.ProtoReflect.Descriptor instead.
func (*EncryptResp) Descriptor() ([]byte, []int) {
	return file_wiresafe_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptResp) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type DecryptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspec    *KeySpec `protobuf:"bytes,1,opt,name=keyspec,proto3" json:"keyspec,omitempty"`
	Ciphertext []byte   `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (x *DecryptReq) Reset() {
	*x = DecryptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wiresafe_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptReq) ProtoMessage() {}

func (x *DecryptReq) ProtoReflect() protoreflect.Message {
	mi := &file_wiresafe_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptReq.ProtoReflect.Descriptor instead.
func (*DecryptReq) Descriptor() ([]byte, []int) {
	return file_wiresafe_proto_rawDescGZIP(), []int{4}
}

func (x *DecryptReq) GetKeyspec() *KeySpec {
	if x != nil {
		return x.Keyspec
	}
	return nil
}

func (x *DecryptReq) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type DecryptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plaintext []byte `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
}

func (x *DecryptResp) Reset() {
	*x = DecryptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wiresafe_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResp) ProtoMessage() {}

func (x *DecryptResp) ProtoReflect() protoreflect.Message {
	mi := &file_wiresafe_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResp.ProtoReflect.Descriptor instead.
func (*DecryptResp) Descriptor() ([]byte, []int) {
	return file_wiresafe_proto_rawDescGZIP(), []int{5}
}

func (x *DecryptResp) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

var File_wiresafe_proto protoreflect.FileDescriptor

var file_wiresafe_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65, 0x22, 0x2b, 0x0a, 0x09, 0x49, 0x6e,
	0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x69,
	0x6e, 0x67, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x6b, 0x65, 0x79, 0x22, 0x3f, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x61, 0x66, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x66, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6b, 0x65, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a, 0x0a, 0x45, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x65,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61,
	0x66, 0x65, 0x2e, 0x4b, 0x65, 0x79, 0x53, 0x70, 0x65, 0x63, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x2d, 0x0a, 0x0b, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74,
	0x22, 0x59, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2b,
	0x0a, 0x07, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65, 0x2e, 0x4b, 0x65, 0x79, 0x53, 0x70,
	0x65, 0x63, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x65, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2b, 0x0a, 0x0b, 0x44,
	0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x69, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x6c, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x32, 0xb3, 0x01, 0x0a, 0x08, 0x57, 0x69, 0x72,
	0x65, 0x53, 0x61, 0x66, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79,
	0x12, 0x11, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65, 0x2e, 0x4b, 0x65, 0x79, 0x53,
	0x70, 0x65, 0x63, 0x1a, 0x13, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x14, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65,
	0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x77, 0x69,
	0x72, 0x65, 0x73, 0x61, 0x66, 0x65, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12,
	0x14, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65,
	0x2e, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x74,
	0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65, 0x3b, 0x77,
	0x69, 0x72, 0x65, 0x73, 0x61, 0x66, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wiresafe_proto_rawDescOnce sync.Once
	file_wiresafe_proto_rawDescData = file_wiresafe_proto_rawDesc
)

func file_wiresafe_proto_rawDescGZIP() []byte {
	file_wiresafe_proto_rawDescOnce.Do(func() {
		file_wiresafe_proto_rawDescData = protoimpl.X.CompressGZIP(file_wiresafe_proto_rawDescData)
	})
	return file_wiresafe_proto_rawDescData
}

var file_wiresafe_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wiresafe_proto_goTypes = []interface{}{
	(*InitReply)(nil),   // 0: wiresafe.InitReply
	(*KeySpec)(nil),     // 1: wiresafe.KeySpec
	(*EncryptReq)(nil),  // 2: wiresafe.EncryptReq
	(*EncryptResp)(nil), // 3: wiresafe.EncryptResp
	(*DecryptReq)(nil),  // 4: wiresafe.DecryptReq
	(*DecryptResp)(nil), // 5: wiresafe.DecryptResp
}
var file_wiresafe_proto_depIdxs = []int32{
	1, // 0: wiresafe.EncryptReq.keyspec:type_name -> wiresafe.KeySpec
	1, // 1: wiresafe.DecryptReq.keyspec:type_name -> wiresafe.KeySpec
	1, // 2: wiresafe.WireSafe.InitKey:input_type -> wiresafe.KeySpec
	2, // 3: wiresafe.WireSafe.encrypt:input_type -> wiresafe.EncryptReq
	4, // 4: wiresafe.WireSafe.Decrypt:input_type -> wiresafe.DecryptReq
	0, // 5: wiresafe.WireSafe.InitKey:output_type -> wiresafe.InitReply
	3, // 6: wiresafe.WireSafe.encrypt:output_type -> wiresafe.EncryptResp
	5, // 7: wiresafe.WireSafe.Decrypt:output_type -> wiresafe.DecryptResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wiresafe_proto_init() }
func file_wiresafe_proto_init() {
	if File_wiresafe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wiresafe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wiresafe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeySpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wiresafe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wiresafe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wiresafe_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wiresafe_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wiresafe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wiresafe_proto_goTypes,
		DependencyIndexes: file_wiresafe_proto_depIdxs,
		MessageInfos:      file_wiresafe_proto_msgTypes,
	}.Build()
	File_wiresafe_proto = out.File
	file_wiresafe_proto_rawDesc = nil
	file_wiresafe_proto_goTypes = nil
	file_wiresafe_proto_depIdxs = nil
}
